/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as maliciousReceiverSol from "./MaliciousReceiver.sol";
export type { maliciousReceiverSol };
export type { Lock } from "./Lock";
export type { MyToken } from "./MyToken";
export type { UBaEducationCredentialsStore } from "./UBaEducationCredentialsStore";
