/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as maliciousReceiverSol from "./MaliciousReceiver.sol";
export { Lock__factory } from "./Lock__factory";
export { MyToken__factory } from "./MyToken__factory";
export { UBaEducationCredentialsStore__factory } from "./UBaEducationCredentialsStore__factory";
